import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useRouter } from 'next/router';

import Link from 'next/link';

export default function Home() {
    const router = useRouter();
    console.log('router', router);
    return (
        <>
            <Head>
                <title>Error Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1>Error - JoeDev</h1>
                <h3>{router.query?.error}</h3>
                <Link href="/">Go Back</Link>
            </main>
        </>
    );
}
