import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });
import { useSession, signIn, signOut } from 'next-auth/react';
import Link from 'next/link';

export default function Home() {
    const { data: session } = useSession();
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1>Welcome - JoeDev</h1>
                <Link href="/dash">Go To a Super Secret Route!</Link>
                {session && session.user ? (
                    <>
                        <p>Signed in as {session.user.email}</p>
                        {session.user.image && (
                            <Image
                                alt="img"
                                src={session.user.image}
                                width="100"
                                height="100"
                            ></Image>
                        )}
                        <button onClick={() => signOut()}>Sign out</button>
                    </>
                ) : (
                    <>
                        <p>Not signed in</p>
                        <button onClick={() => signIn()}>Sign in</button>
                    </>
                )}
            </main>
        </>
    );
}
